name: Deploy Staging Environment

# events
on:
  push:
    branches:
      - test

# jobs that execute on self-hosted runner on local machine
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        # action to checkout code from repo
        uses: actions/checkout@v4
      
      - name: Inject .env.staging Secrets
        run: |
          echo "UPSTASH_REDIS_REST_URL=${{ secrets.UPSTASH_REDIS_REST_URL }}" >> .env.staging
          echo "UPSTASH_REDIS_REST_TOKEN=${{ secrets.UPSTASH_REDIS_REST_TOKEN }}" >> .env.staging
          echo "GEMINI_MODEL=${{ secrets.GEMINI_MODEL }}" >> .env.staging
          echo "GEMINI_EMBEDDING_MODEL=${{ secrets.GEMINI_EMBEDDING_MODEL }}" >> .env.staging
          echo "GOOGLE_GENERATIVE_AI_API_KEY=${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}" >> .env.staging
        
      - name: Build and Sin Up Docker Container
        run: docker compose up --build -d
      
      - name: Clean Up Old Images (Save Disk Space)
        run: docker image prune -f